# Generated by Django 4.1.1 on 2022-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_playersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
