# Generated by Django 4.1.1 on 2022-09-20 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_playersmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersmodel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.teamsmodel'),
        ),
        migrations.AlterField(
            model_name='teamsmodel',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.stadiumsmodel'),
        ),
    ]
